PLAYER_HOME_BLACK = 'HOME_BLACK'
PLAYER_HOME_WHITE = 'HOME_WHITE'

COLOR_BLACK = 'BLACK'
COLOR_WHITE = 'WHITE'

DIRECTION_BLACK = 1
DIRECTION_WHITE = -1

def GET_OPPOSITE_COLOR(color: str):
    return COLOR_WHITE if color == COLOR_BLACK else COLOR_BLACK
